import * as path from "node:path";
import * as fs from "node:fs/promises";
import { LanguageEntry } from "./types";
import { ensureDir, toServedPath } from "./utils";

export async function generateLoaderArtifacts(opts: {
  workspaceRoot: string;
  srcDir: string;
  outputRoot: string;
  baseLocaleCode: string;
  languages: LanguageEntry[];
  baseFiles: Array<{ baseFileAbs: string; outDirAbs: string; targets: string[] }>;
  updateMode: "merge" | "overwrite" | "recreate";
  languagesJsonPath?: string;
}): Promise<{ loaderPath: string; readmePath: string; languageSelectorPath: string; packageJsonUpdated: boolean; packageJsonReason?: string }> {
  const { workspaceRoot, srcDir, outputRoot, baseLocaleCode, languages, baseFiles: _baseFiles, updateMode, languagesJsonPath } = opts;



  const translateDirAbs = path.join(workspaceRoot, srcDir, "translate");
  await ensureDir(translateDirAbs);

  const _outputRootAbs = path.join(workspaceRoot, outputRoot);

  // Web path the locales are served from — outputRoot relative to the source folder
  // (e.g. "projects/app/src" + "projects/app/src/assets/i18n" -> "./assets/i18n/").
  const outputRootRelative = toServedPath(srcDir, outputRoot);

  const loaderPath = path.join(translateDirAbs, "tg-translate-loader.ts");
  const readmePath = path.join(translateDirAbs, "readme.md");

  const loaderSource = `import { HttpClient } from "@angular/common/http";
import { TranslateLoader } from "@ngx-translate/core";
import { Observable, of } from "rxjs";
import { map, catchError, tap } from "rxjs/operators";

export type TgTranslations = Record<string, any>;

export class TgTranslationLoader implements TranslateLoader {
  constructor(
    private http: HttpClient,
    private prefix: string = "${outputRootRelative}",
    private suffix: string = ".json"    
  ) {}

  public getTranslation(lang: string): Observable<TgTranslations> { 

    const url = \`\${this.prefix}\${lang}\${this.suffix}\`;

    return this.http.get<TgTranslations>(url).pipe(    
      catchError(err => {
        console.error(\`[TgTranslationLoader] ✗ Failed to load \${url}:\`, err);
        return of({} as TgTranslations);
      })
    );
  }
}
`;

  const readme = `# TgTranslationLoader

This folder is auto-generated by the **Angular Translation Extractor** extension.

It contains:
- \`tg-translate-loader.ts\` - An Angular HTTP loader that directly loads locale JSON files
- \`tg-language-selector.component.ts\` - A standalone component to switch languages
- \`readme.md\` - This file with usage and configuration guidance

## About the Extractor

The Angular Translation Extractor intelligently scans your TypeScript and HTML files to extract user-facing strings for translation.

### What Gets Extracted

✅ **Extracted strings:**
- Strings in \`@Component\` decorators (template, selector, etc.)
- Alert/confirmation messages: \`alert()\`, \`confirm()\`, \`prompt()\`
- Message service calls: \`this.toastr.error()\`, \`this.snackBar.open()\`, \`showMessage()\`
- Object properties: \`title\`, \`message\`, \`placeholder\`, \`label\`, \`tooltip\`, \`errorMessage\`, etc.
- HTML text content and attribute values

❌ **Skipped strings:**
- Control flow conditions: \`if\`, \`for\`, \`while\`, \`switch\`, ternary operators
- Import/export statements
- Technical identifiers and constants
- URLs, paths, and module specifiers
- State object values

### Automatic Translation Services

The extension includes **built-in automatic translation** - no API key or account required!

You can choose between two free translation services:

#### Option 1: Google Translate (Recommended) ⭐

Google Translate provides **high-quality translations** using the same public API as translate.google.com.

**Pros:**
- Excellent translation quality
- Fast and reliable
- Handles context well
- Free to use

**Cons:**
- Rate limited (built-in delays prevent blocking)
- May change their API without notice (though unlikely)


#### Configuration

Choose your translation service in VS Code settings:

\`\`\`json
{
  "i18nExtractor.autoTranslate": true,
  "i18nExtractor.autoTranslateDefaultLanguage": false
}
\`\`\`

Key settings:
- \`i18nExtractor.autoTranslate\` - Enable/disable automatic translation (default: \`true\`)
- \`i18nExtractor.autoTranslateDefaultLanguage\` - Translate the default language (default: \`false\`)
- \`i18nExtractor.googleTranslateDelay\` - Delay between requests in milliseconds (default: \`500\`, minimum: \`100\`)

## Configuration Settings

Paths are **not configurable** — they are detected from your \`angular.json\`: the source folder is the
project's \`sourceRoot\`, locales are written to \`<sourceRoot>/assets/i18n\`, the languages list is
\`<sourceRoot>/app/core/json/language-code.json\`, and the bootstrap file comes from the build target.

The remaining behaviour can be configured through VS Code settings (\`settings.json\`) or the Settings UI:

| Setting ID | Description | Default |
|------------|-------------|---------|
| \`default: true\` in language JSON | Base/default source language | Required on one language entry |
| \`i18nExtractor.aggressiveMode\` | Function-parameter extraction mode: \`low\`, \`moderate\`, \`high\` | \`moderate\` |
| \`i18nExtractor.aggressiveModeAllowCallRegex\` | Regex allowlist matched against full call source (priority over \`aggressiveMode\`) | \`["^alert\\\\s*\\\\(", "^confirm\\\\s*\\\\(", "^prompt\\\\s*\\\\("]\` |
| \`i18nExtractor.aggressiveModeAllowContextRegex\` | Regex allowlist matched against argument context (priority over \`aggressiveMode\`) | \`["^window\\\\.alert\\\\(arg#1\\\\)$", "^window\\\\.confirm\\\\(arg#1\\\\)$", "^window\\\\.prompt\\\\(arg#1\\\\)$"]\` |
| \`i18nExtractor.minStringLength\` | Ignore strings shorter than this | \`2\` |
| \`i18nExtractor.ignoreGlobs\` | Glob patterns to ignore | \`["**/*.test.*", "**/*.spec.*", "**/node_modules/**", "**/dist/**", "**/build/**", "**/.next/**", "**/.angular/**", "**/app.html", "**/index.html", "**/assets/**", "**/environments/**", "**/.agent/**", "**/.vscode/**"]\` |
| \`i18nExtractor.skipGlobs\` | Additional glob patterns to skip | \`[]\` |
| \`i18nExtractor.htmlAttributeNames\` | HTML attributes to extract | \`["title", "alt", "placeholder", "aria-label", "aria-placeholder"]\` |
| \`i18nExtractor.angularBootstrapStyle\` | \`standalone\` or \`module\` | \`standalone\` |
| \`i18nExtractor.updateMode\` | Source source updates: \`merge\`, \`overwrite\`, \`recreate\` | \`merge\` |
| \`i18nExtractor.autoTranslate\` | Automatically translate keys | \`true\` |
| \`i18nExtractor.autoTranslateDefaultLanguage\` | Translate source language (usually false) | \`false\` |
| \`i18nExtractor.googleTranslateDelay\` | Delay between translation API calls (ms) | \`500\` |
| \`i18nExtractor.useTranslateCommand\` | Run custom command after extration | \`false\` |
| \`i18nExtractor.translateCommand\` | Custom translation command | \`npx-translate\` |
| \`i18nExtractor.translateArgsTemplate\` | Arguments for custom command | \`["--input", "{baseFile}", "--outDir", "{outDir}", "--from", "{baseLocale}", "--to", "{targetLocale}"]\` |

### Language Configuration File

The \`<sourceRoot>/app/core/json/language-code.json\` file defines your supported languages:

\`\`\`json
[
  {
    "rank": 1,
    "code": "en-US",
    "englishName": "English (United States)",
    "nativeName": "English (United States)",
    "flag": "https://flagcdn.com/w40/us.png",
    "default": true,
    "active": true
  },
  {
    "rank": 2,
    "code": "pt-BR",
    "englishName": "Portuguese (Brazil)",
    "nativeName": "Português (Brasil)",
    "flag": "https://flagcdn.com/w40/br.png",
    "default": false,
    "active": true
  },
  {
    "rank": 3,
    "code": "pt-PT",
    "englishName": "Portuguese (Portugal)",
    "nativeName": "Português (Portugal)",
    "flag": "https://flagcdn.com/w40/pt.png",
    "default": false,
    "active": false
  },
  {
    "rank": 4,
    "code": "en-ES",
    "englishName": "English (Spain)",
    "nativeName": "English (Spain)",
    "flag": "https://flagcdn.com/w40/es.png",
    "default": false,
    "active": true
  },
  {
    "rank": 5,
    "code": "fr-FR",
    "englishName": "French (France)",
    "nativeName": "Français (France)",
    "flag": "https://flagcdn.com/w40/fr.png",
    "default": false,
    "active": true
  },
  {
    "rank": 6,
    "code": "it-IT",
    "englishName": "Italian (Italy)",
    "nativeName": "Italiano (Italia)",
    "flag": "https://flagcdn.com/w40/it.png",
    "default": false,
    "active": true
  },
  {
    "rank": 7,
    "code": "zh-CN",
    "englishName": "Chinese (Simplified, China)",
    "nativeName": "中文 (中国)",
    "flag": "https://flagcdn.com/w40/cn.png",
    "default": false,
    "active": true
  }
]
\`\`\`

**Note:** If this file doesn't exist, the extension will automatically create it with a default set of languages. Properties like \`englishName\`, \`nativeName\`, and \`flag\` are auto-filled if missing.

#### How It Works

When you run the extraction command:
1. Extracts all user-facing strings from your code
2. Generates a base language JSON file (e.g., \`en.json\`) with all extracted strings
3. **Automatically translates** the base file to all configured target languages using your chosen service
4. Creates translated JSON files (e.g., \`pt.json\`, \`es.json\`, \`fr.json\`, etc.)

#### Translation Process Example

\`\`\`
Base language file: src/assets/i18n/en-US.json
{
  "APP": {
    "HOME": {
      "TITLE": "Welcome",
      "MESSAGE": "Hello World"
    }
  }
}

↓ Translation Service (Google)

Target files:
- src/assets/i18n/pt-BR.json
- src/assets/i18n/es-ES.json
- src/assets/i18n/fr-FR.json
\`\`\`

#### Rate Limiting Protection

The extension includes automatic rate limiting protection:
- Default 500ms delay between translation requests
- Prevents temporary blocking from the translation service
- Configurable via \`googleTranslateDelay\` setting
- Progress shown in the output panel during translation

#### Translation Quality Notes

**Google Translate:**
- Produces professional-quality translations suitable for production
- Can be used directly in applications
- Minimal manual review needed


#### Disabling Automatic Translation

To disable automatic translation entirely:

\`\`\`json
{
  "i18nExtractor.autoTranslate": false
}
\`\`\`

Or to skip translating the default language (source):

\`\`\`json
{
  "i18nExtractor.autoTranslateDefaultLanguage": false  // don't translate default language
}
\`\`\`

Or use a custom translation command instead.

#### Tips for Using Auto-Translated Content

- Translations are saved to JSON files and can be manually refined later
- Professional translators can review and improve auto-translated content
- Re-running extraction with \`updateMode: "merge"\` preserves existing manual translations

#### Troubleshooting Translation Issues

If translations fail:
1. Check your internet connection
2. Increase the \`googleTranslateDelay\` setting (try \`1000\` or \`2000\` ms)
3. Check the Output panel for detailed error messages
4. Retry extraction after a short delay if Google rate-limits requests

## What This Loader Does

The loader reads locale JSON files from:
- \`${outputRoot}\`

Each locale gets its own JSON file. The loader directly loads the JSON file for the requested language.

## Language Code Fallback

The loader automatically handles language code fallback:
- When requesting \`en-US\`, it first tries to load \`en-US.json\`
- If not found, it falls back to \`en.json\` (main language code)

Example: Instead of maintaining \`en-US.json\`, \`en-GB.json\`, \`en-CA.json\`, you can just have one \`en.json\` that serves all English variants.

## Usage in Angular Standalone App

\`\`\`typescript
import { ApplicationConfig } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { HttpClient } from '@angular/common/http';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import { importProvidersFrom } from "@angular/core";
import { TgTranslationLoader } from "./translate/tg-translate-loader";

export function HttpLoaderFactory(http: HttpClient): TranslateLoader {
  return new TgTranslationLoader(http, "${outputRootRelative}");
}

export const appConfig: ApplicationConfig = {
  providers: [
    provideHttpClient(),
    importProvidersFrom(
      TranslateModule.forRoot({
        defaultLanguage: "${baseLocaleCode}",
        loader: {
          provide: TranslateLoader,
          useFactory: HttpLoaderFactory,
          deps: [HttpClient]
        }
      })
    )
  ]
};
\`\`\`

## Usage in Component

\`\`\`typescript
import { Component, inject } from '@angular/core';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [TranslateModule],
  template: \`
    <h1>{{ 'app.title' | translate }}</h1>
    <p>{{ 'app.welcome' | translate }}</p>
    <button (click)="switchLanguage('pt')">Português</button>
    <button (click)="switchLanguage('es')">Español</button>
  \`
})
export class AppComponent {
  private translate = inject(TranslateService);

  switchLanguage(lang: string) {
    this.translate.use(lang);
  }
}
\`\`\`
Using the Language Selector

Import the standalone component and use it in your templates. You can configure the mode (\`white\` or \`dark\`):

\`\`\`typescript
import { Component } from '@angular/core';
import { TgLanguageSelectorComponent } from './translate/tg-language-selector.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [TgLanguageSelectorComponent],
  template: \`
    <nav>
      <h1>My App</h1>
      <!-- Default (white) mode -->
      <tg-language-selector></tg-language-selector>

      or
      
      <!-- Light Mode -->
      <tg-language-selector [mode]="'white'"></tg-language-selector>

      <!-- Dark mode -->
      <tg-language-selector [mode]="'dark'"></tg-language-selector>
    </nav>
  \`
})
export class HeaderComponent {}
\`\`\`

## 
## Configuration Options

The loader accepts the following options:

- \`prefix\` (optional): Base URL to the locale root folder (default: \`"${outputRootRelative}"\`)
- \`suffix\` (optional): File suffix for JSON files (default: \`".json"\`)

Example with custom configuration:
\`\`\`typescript
export function HttpLoaderFactory(http: HttpClient): TranslateLoader {
  return new TgTranslationLoader(
    http,
    "./custom/path/",  // custom prefix
    ".json"            // suffix
  );
}
\`\`\`

## Files Generated

- Loader: \`${path.posix.join(srcDir, "translate", "tg-translate-loader.ts")}\`
- Readme: \`${path.posix.join(srcDir, "translate", "readme.md")}\`

## Configured Languages

${languages.map(l => `- **${l.code}** - ${l.englishName || l.code}${l.default ? ' (default)' : ''}`).join("\n")}

## Extension Configuration

Access settings via: **File → Preferences → Settings** → Search for "Angular Translation Extractor"

Key settings:
- \`i18nExtractor.autoTranslate\` - Automatically translate to target languages (default: \`true\`)
- \`i18nExtractor.autoTranslateDefaultLanguage\` - Translate the default language (default: \`false\`)
- \`i18nExtractor.googleTranslateDelay\` - Delay between translation requests in milliseconds (default: \`500\`)

JSON files are always generated under \`${outputRoot}\` — detected from your \`angular.json\`, not configured.



## Notes


- This loader uses Angular HttpClient and is designed for runtime use in Angular apps
- Ensure the \`${outputRoot}\` folder is served as static assets
- The extension automatically updates \`main.ts\` to wire up the TranslateModule (can be disabled in settings)
- All generated files can be safely regenerated by running the extraction command again

## Need Help?

Run the command: **Extract translations (All app)** from the VS Code Command Palette (Ctrl+Shift+P)
`;

  const allowOverwrite = updateMode !== "merge";

  if (await shouldWriteFile(loaderPath, allowOverwrite)) {
    await fs.writeFile(loaderPath, loaderSource, "utf8");
  }

  if (await shouldWriteFile(readmePath, allowOverwrite)) {
    await fs.writeFile(readmePath, readme, "utf8");
  }

  const selectorComponentPath = path.join(translateDirAbs, "tg-language-selector.component.ts");
  const selectorTemplatePath = path.join(translateDirAbs, "tg-language-selector.component.html");
  const selectorStylePath = path.join(translateDirAbs, "tg-language-selector.component.css");

  // Determine runtime URL for languages JSON
  let languagesJsonUrl = 'app/core/json/language-code.json';
  if (languagesJsonPath) {
    // We try to make it relative to srcDir, assuming srcDir is the web root (or effectively so for assets)
    // If srcDir is "src", and languagesJsonPath is "src/assets/foo.json", result is "assets/foo.json"
    const rel = path.relative(srcDir, languagesJsonPath);
    if (!rel.startsWith('..') && !path.isAbsolute(rel)) {
      languagesJsonUrl = rel.replace(/\\/g, '/');
    }
  }

  // Emit the signal / new-control-flow (@if, @for) variant only for Angular 17+.
  // Older projects (or when the version can't be detected) get the universally
  // compatible *ngIf / @Input variant.
  const angularMajor = await detectAngularMajor(workspaceRoot);
  const useModernSyntax = angularMajor >= 17;
  const selectorComponent = useModernSyntax
    ? getTgLanguageSelectorComponent(languagesJsonUrl)
    : getTgLanguageSelectorComponentLegacy(languagesJsonUrl);
  const selectorTemplate = useModernSyntax
    ? getLanguageSelectorTemplate()
    : getLanguageSelectorTemplateLegacy();
  const selectorStyle = getLanguageSelectorStyle();


  await fs.writeFile(selectorComponentPath, selectorComponent, "utf8");
  await fs.writeFile(selectorTemplatePath, selectorTemplate, "utf8");
  await fs.writeFile(selectorStylePath, selectorStyle, "utf8");


  return {
    loaderPath,
    readmePath,
    languageSelectorPath: selectorComponentPath,
    packageJsonUpdated: false
  };
}

async function shouldWriteFile(fileAbs: string, allowOverwrite: boolean): Promise<boolean> {
  if (allowOverwrite) return true;
  try {
    await fs.stat(fileAbs);
    return false;
  } catch {
    return true;
  }
}

function getTgLanguageSelectorComponent(languagesJsonUrl: string): string {
  return `/* 
 * This file is auto-generated by the Angular Translation Extractor extension.
 * Any manual changes to this file may be lost when the extension runs again.
 */
import { Component, ElementRef, HostListener, input, OnInit, signal, viewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateService } from '@ngx-translate/core';
import { HttpClient } from '@angular/common/http';

export interface TgLanguage {
  code: string;
  englishName?: string;
  nativeName?: string;
  flag?: string;
  default?: boolean;
  active?: boolean;
  rank?: number;
}

@Component({
  selector: 'tg-language-selector',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './tg-language-selector.component.html',
  styleUrls: ['./tg-language-selector.component.css']
})
export class TgLanguageSelectorComponent implements OnInit {
  mode = input<'white' | 'dark'>('white');
  /** Vertical open direction. 'auto' flips upward when there is not enough room below. */
  direction = input<'auto' | 'up' | 'down'>('auto');
  /** Horizontal alignment. 'auto' anchors to the right edge when a left-anchored menu would overflow. */
  align = input<'auto' | 'left' | 'right'>('auto');
  /** Stacking context for the selector — raise it above overlays, sticky footers, etc. */
  zIndex = input<number | string>(1000);
  /** Class applied to the root when in white / dark mode — override to match your design system. */
  whiteModeClass = input<string>('white-mode');
  darkModeClass = input<string>('dark-mode');
  /** True when the dropdown should open upward (computed from direction / viewport space). */
  readonly dropUp = signal(false);
  /** True when the dropdown should anchor to its right edge (computed from align / viewport space). */
  readonly alignRight = signal(false);
  /** Kept in sync with the dropdown's CSS max-height so the flip decision is accurate. */
  private readonly dropdownMaxHeightPx = 320;
  /** Approximate dropdown width used to decide horizontal overflow. */
  private readonly dropdownMinWidthPx = 160;
  readonly languages = signal<TgLanguage[]>([]);
  readonly currentLanguage = signal<TgLanguage | null>(null);
  readonly isOpen = signal(false);
  readonly rootRef = viewChild<ElementRef<HTMLElement>>('root');

  constructor(
    private translateService: TranslateService,
    private http: HttpClient
  ) { }

  ngOnInit(): void {

    if (this.getLanguagesFromSession()) {
      return;
    }
    this.loadLanguages();
  }

  private loadLanguages(): void {

    this.http.get<TgLanguage[]>('${languagesJsonUrl}')
      .subscribe({
        next: (langs) => {
          const activeLanguages = langs
            .filter(l => l.active !== false)
            .sort((a, b) => (a.rank ?? 999) - (b.rank ?? 999));
          this.languages.set(activeLanguages);

          const currentLanguages = this.languages();
          const defaultLang = currentLanguages.find(l => l.default) || currentLanguages[0];
          if (defaultLang) {
            this.translateService.setDefaultLang(defaultLang.code);
            this.translateService.use(defaultLang.code);
          }

          const currentLang = this.translateService.currentLang || this.translateService.defaultLang;
          if (currentLang) {
            this.currentLanguage.set(currentLanguages.find(l => l.code === currentLang) || currentLanguages[0] || null);
          } else if (currentLanguages.length > 0) {
            this.currentLanguage.set(currentLanguages[0]);
          }
          sessionStorage.setItem('languages', JSON.stringify(currentLanguages));
        },
        error: (err) => {
          // Fallback or error handling
          if (!this.currentLanguage() && this.languages().length > 0) {
            this.currentLanguage.set(this.languages()[0]);
          }
          console.error('Failed to load languages from ${languagesJsonUrl}', err);
        }
      });
  }

  getLanguagesFromSession() {
    const savedLangCode = sessionStorage.getItem('selectedLanguage');
    const savedLanguages = sessionStorage.getItem('languages');
    if (savedLanguages) {
      var defaultLang = JSON.parse(savedLanguages).find((l: TgLanguage) => l.default) || JSON.parse(savedLanguages)[0];
      if (defaultLang) {
        this.translateService.setDefaultLang(defaultLang.code);
      }
      const parsedLanguages = JSON.parse(savedLanguages) as TgLanguage[];
      this.languages.set(parsedLanguages);
      const savedLang = parsedLanguages.find(l => l.code === savedLangCode);
      if (savedLang) {
        this.currentLanguage.set(savedLang);
        this.translateService.use(savedLang.code);
        return true;
      }
    }
    return false;
  }

  selectLanguage(language: TgLanguage): void {
    this.currentLanguage.set(language);
    this.translateService.use(language.code);
    this.isOpen.set(false);

    // Save preference to sessionStorage
    sessionStorage.setItem('selectedLanguage', language.code);
  }

  toggleDropdown(event: Event): void {
    event.stopPropagation();
    const willOpen = !this.isOpen();
    if (willOpen) {
      this.updateDropdownPlacement();
    }
    this.isOpen.set(willOpen);
  }

  /**
   * Decide where the dropdown opens — vertically (up/down) and horizontally
   * (left/right). Each axis honours an explicit input value, otherwise it is
   * auto-detected from the space available around the trigger in the viewport.
   */
  private updateDropdownPlacement(): void {
    const rect = this.rootRef()?.nativeElement?.getBoundingClientRect();

    // Vertical: flip up only when there isn't room below but there is more above.
    const dir = this.direction();
    if (dir === 'up') {
      this.dropUp.set(true);
    } else if (dir === 'down' || !rect) {
      this.dropUp.set(false);
    } else {
      const spaceBelow = window.innerHeight - rect.bottom;
      const spaceAbove = rect.top;
      this.dropUp.set(spaceBelow < this.dropdownMaxHeightPx && spaceAbove > spaceBelow);
    }

    // Horizontal: anchor right only when a left-anchored menu would overflow and
    // there is more room to the left.
    const align = this.align();
    if (align === 'right') {
      this.alignRight.set(true);
    } else if (align === 'left' || !rect) {
      this.alignRight.set(false);
    } else {
      const spaceRight = window.innerWidth - rect.left;
      const spaceLeft = rect.right;
      this.alignRight.set(spaceRight < this.dropdownMinWidthPx && spaceLeft > spaceRight);
    }
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: Event): void {
    const host = this.rootRef()?.nativeElement;
    if (!host || !host.contains(event.target as Node)) {
      this.isOpen.set(false);
    }
  }

  @HostListener('document:keydown.escape')
  onEscape(): void {
    this.isOpen.set(false);
  }

  getDisplayName(language: TgLanguage): string {
    return language?.nativeName || language?.englishName || language?.code?.toUpperCase() || '';
  }
}
`;
}

function getLanguageSelectorTemplate(): string {
  return `<div #root class="language-selector"
  [ngClass]="mode() === 'dark' ? darkModeClass() : whiteModeClass()"
  [style.z-index]="zIndex()"
  (click)="toggleDropdown($event)">
  <div class="current-language">
    @if (currentLanguage()?.flag) {
    <img
      aria-label="Current language flag"
      [src]="currentLanguage()?.flag"
      [alt]="getDisplayName(currentLanguage()!)"
      class="flag-icon">
    }
    <span class="language-name language-name-full">{{
      getDisplayName(currentLanguage()!) }}</span>
    <span class="language-name language-name-compact">{{
      currentLanguage()?.code?.toUpperCase() }}</span>
    <svg class="dropdown-icon" [class.open]="isOpen()" width="16" height="16"
      viewBox="0 0 16 16" fill="currentColor">
      <path d="M4 6l4 4 4-4z" />
    </svg>
  </div>

  @if (isOpen()) {
  <div class="language-dropdown" [class.drop-up]="dropUp()" [class.align-right]="alignRight()">
    @for (language of languages(); track language.code) {
    <div
      class="language-option"
      [class.selected]="language.code === currentLanguage()?.code"
      (click)="selectLanguage(language); $event.stopPropagation()">
      @if (language.flag) {
      <img
        aria-label="Language flag for {{ getDisplayName(language) }}"
        [src]="language.flag"
        [alt]="getDisplayName(language)"
        class="flag-icon">
      }
      <span class="language-name language-name-full"
        [title]="language.englishName">{{ getDisplayName(language) }}</span>
      <span class="language-name language-name-compact">{{
        language.code.toUpperCase() }}</span>
      @if (language.code === currentLanguage()?.code) {
      <svg class="check-icon"
        width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
        <path
          d="M13.854 3.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 9.793l6.646-6.647a.5.5 0 0 1 .708 0z" />
      </svg>
      }
    </div>
    }
  </div>
  }
</div>
`;
}

/** Reads the target project's @angular/core major version (0 = unknown). */
async function detectAngularMajor(workspaceRoot: string): Promise<number> {
  try {
    const pkgRaw = await fs.readFile(path.join(workspaceRoot, "package.json"), "utf8");
    const pkg = JSON.parse(pkgRaw) as { dependencies?: Record<string, string>; devDependencies?: Record<string, string> };
    const spec = pkg.dependencies?.["@angular/core"] ?? pkg.devDependencies?.["@angular/core"] ?? "";
    const match = spec.match(/(d+)/);
    return match ? parseInt(match[1], 10) : 0;
  } catch {
    return 0;
  }
}

function getTgLanguageSelectorComponentLegacy(languagesJsonUrl: string): string {
  return `/*
 * This file is auto-generated by the Angular Translation Extractor extension.
 * Any manual changes to this file may be lost when the extension runs again.
 */
import { Component, ElementRef, HostListener, Input, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateService } from '@ngx-translate/core';
import { HttpClient } from '@angular/common/http';

export interface TgLanguage {
  code: string;
  englishName?: string;
  nativeName?: string;
  flag?: string;
  default?: boolean;
  active?: boolean;
  rank?: number;
}

@Component({
  selector: 'tg-language-selector',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './tg-language-selector.component.html',
  styleUrls: ['./tg-language-selector.component.css']
})
export class TgLanguageSelectorComponent implements OnInit {
  /** Vertical open direction. 'auto' flips upward when there is not enough room below. */
  @Input() direction: 'auto' | 'up' | 'down' = 'auto';
  /** Horizontal alignment. 'auto' anchors to the right edge when a left-anchored menu would overflow. */
  @Input() align: 'auto' | 'left' | 'right' = 'auto';
  /** Stacking context for the selector — raise it above overlays, sticky footers, etc. */
  @Input() zIndex: number | string = 1000;
  /** Class applied to the root when in white / dark mode — override to match your design system. */
  @Input() whiteModeClass = 'white-mode';
  @Input() darkModeClass = 'dark-mode';
  @Input() mode: 'white' | 'dark' = 'white';
  /** True when the dropdown should open upward (computed from direction / viewport space). */
  dropUp = false;
  /** True when the dropdown should anchor to its right edge (computed from align / viewport space). */
  alignRight = false;
  private readonly dropdownMaxHeightPx = 320;
  private readonly dropdownMinWidthPx = 160;
  languages: TgLanguage[] = [];
  currentLanguage: TgLanguage | null = null;
  isOpen = false;
  @ViewChild('root') rootRef?: ElementRef<HTMLElement>;

  constructor(
    private translateService: TranslateService,
    private http: HttpClient
  ) { }

  ngOnInit(): void {

    if (this.getLanguagesFromSession()) {
      return;
    }
    this.loadLanguages();
  }

  private loadLanguages(): void {

    this.http.get<TgLanguage[]>('${languagesJsonUrl}')
      .subscribe({
        next: (langs) => {
          this.languages = langs
            .filter(l => l.active !== false)
            .sort((a, b) => (a.rank ?? 999) - (b.rank ?? 999));

          const defaultLang = this.languages.find(l => l.default) || this.languages[0];
          if (defaultLang) {
            this.translateService.setDefaultLang(defaultLang.code);
            this.translateService.use(defaultLang.code);
          }

          const currentLang = this.translateService.currentLang || this.translateService.defaultLang;
          if (currentLang) {
            this.currentLanguage = this.languages.find(l => l.code === currentLang) || this.languages[0] || null;
          } else if (this.languages.length > 0) {
            this.currentLanguage = this.languages[0];
          }
          sessionStorage.setItem('languages', JSON.stringify(this.languages));
        },
        error: (err) => {
          // Fallback or error handling
          if (!this.currentLanguage && this.languages.length > 0) {
            this.currentLanguage = this.languages[0];
          }
          console.error('Failed to load languages from ${languagesJsonUrl}', err);
        }
      });
  }

  getLanguagesFromSession() {
    const savedLangCode = sessionStorage.getItem('selectedLanguage');
    const savedLanguages = sessionStorage.getItem('languages');
    if (savedLanguages) {
      const parsedLanguages = JSON.parse(savedLanguages) as TgLanguage[];
      const defaultLang = parsedLanguages.find(l => l.default) || parsedLanguages[0];
      if (defaultLang) {
        this.translateService.setDefaultLang(defaultLang.code);
      }
      this.languages = parsedLanguages;
      const savedLang = parsedLanguages.find(l => l.code === savedLangCode);
      if (savedLang) {
        this.currentLanguage = savedLang;
        this.translateService.use(savedLang.code);
        return true;
      }
    }
    return false;
  }

  selectLanguage(language: TgLanguage): void {
    this.currentLanguage = language;
    this.translateService.use(language.code);
    this.isOpen = false;

    // Save preference to sessionStorage
    sessionStorage.setItem('selectedLanguage', language.code);
  }

  toggleDropdown(event: Event): void {
    event.stopPropagation();
    const willOpen = !this.isOpen;
    if (willOpen) {
      this.updateDropdownPlacement();
    }
    this.isOpen = willOpen;
  }

  /**
   * Decide where the dropdown opens — vertically (up/down) and horizontally
   * (left/right). Each axis honours an explicit input value, otherwise it is
   * auto-detected from the space available around the trigger in the viewport.
   */
  private updateDropdownPlacement(): void {
    const rect = this.rootRef?.nativeElement?.getBoundingClientRect();

    const dir = this.direction;
    if (dir === 'up') {
      this.dropUp = true;
    } else if (dir === 'down' || !rect) {
      this.dropUp = false;
    } else {
      const spaceBelow = window.innerHeight - rect.bottom;
      const spaceAbove = rect.top;
      this.dropUp = spaceBelow < this.dropdownMaxHeightPx && spaceAbove > spaceBelow;
    }

    const align = this.align;
    if (align === 'right') {
      this.alignRight = true;
    } else if (align === 'left' || !rect) {
      this.alignRight = false;
    } else {
      const spaceRight = window.innerWidth - rect.left;
      const spaceLeft = rect.right;
      this.alignRight = spaceRight < this.dropdownMinWidthPx && spaceLeft > spaceRight;
    }
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: Event): void {
    const host = this.rootRef?.nativeElement;
    if (!host || !host.contains(event.target as Node)) {
      this.isOpen = false;
    }
  }

  @HostListener('document:keydown.escape')
  onEscape(): void {
    this.isOpen = false;
  }

  getDisplayName(language: TgLanguage): string {
    return language?.nativeName || language?.englishName || language?.code?.toUpperCase() || '';
  }
}
`;
}

function getLanguageSelectorTemplateLegacy(): string {
  return `<div #root class="language-selector"
  [ngClass]="mode === 'dark' ? darkModeClass : whiteModeClass"
  [style.z-index]="zIndex"
  (click)="toggleDropdown($event)">
  <div class="current-language">
    <img
      *ngIf="currentLanguage?.flag"
      aria-label="Current language flag"
      [src]="currentLanguage?.flag"
      [alt]="getDisplayName(currentLanguage!)"
      class="flag-icon">
    <span class="language-name language-name-full">{{
      getDisplayName(currentLanguage!) }}</span>
    <span class="language-name language-name-compact">{{
      currentLanguage?.code?.toUpperCase() }}</span>
    <svg class="dropdown-icon" [class.open]="isOpen" width="16" height="16"
      viewBox="0 0 16 16" fill="currentColor">
      <path d="M4 6l4 4 4-4z" />
    </svg>
  </div>

  <div class="language-dropdown" *ngIf="isOpen" [class.drop-up]="dropUp" [class.align-right]="alignRight">
    <div
      *ngFor="let language of languages"
      class="language-option"
      [class.selected]="language.code === currentLanguage?.code"
      (click)="selectLanguage(language); $event.stopPropagation()">
      <img
        *ngIf="language.flag"
        aria-label="Language flag for {{ getDisplayName(language) }}"
        [src]="language.flag"
        [alt]="getDisplayName(language)"
        class="flag-icon">
      <span class="language-name language-name-full"
        [title]="language.englishName">{{ getDisplayName(language) }}</span>
      <span class="language-name language-name-compact">{{
        language.code.toUpperCase() }}</span>
      <svg *ngIf="language.code === currentLanguage?.code" class="check-icon"
        width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
        <path
          d="M13.854 3.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 9.793l6.646-6.647a.5.5 0 0 1 .708 0z" />
      </svg>
    </div>
  </div>
</div>
`;
}

function getLanguageSelectorStyle(): string {
  return `.language-selector {
  position: relative;
  display: inline-block;
  z-index: 1000;
}

/* Default white mode variables */
:host {
  display: block;
  --background: #ffffff;
  --border-color: #e0e0e0;
  --hover-background: #f5f5f5;
  --hover-border-color: #d0d0d0;
  --text-color: #333333;
  --icon-color: #666666;
  --selected-background: #e3f2fd;
  --selected-text-color: #1976d2;
}

/* White mode (explicit). Keyed on the root class so the class name stays
   customizable via the whiteModeClass/darkModeClass inputs (defaults below). */
.language-selector.white-mode {
  --background: #ffffff;
  --border-color: #e0e0e0;
  --hover-background: #f5f5f5;
  --hover-border-color: #d0d0d0;
  --text-color: #333333;
  --icon-color: #666666;
  --selected-background: #e3f2fd;
  --selected-text-color: #1976d2;
}

/* Dark mode */
.language-selector.dark-mode {
  --background: #2d2d2d;
  --border-color: #404040;
  --hover-background: #3d3d3d;
  --hover-border-color: #505050;
  --text-color: #e0e0e0;
  --icon-color: #b0b0b0;
  --selected-background: #1565c0;
  --selected-text-color: #ffffff;
}

.current-language {
  display: flex;
  align-items: center;
  height: 40px;
  gap: 8px;
  padding: 8px 12px;
  background: var(--background);
  border: 1px solid var(--border-color);
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s ease;
  min-width: 150px;
}

/* Compact display on small screens */
@media (max-width: 640px) {
  .current-language {
    min-width: auto;
    padding: 8px;
    gap: 4px;
  }

  .language-name-full {
    display: none;
  }

  .language-name-compact {
    display: inline;
  }

  .language-dropdown {
    min-width: 160px;
  }
}

/* Hide compact label by default */
.language-name-compact {
  display: none;
}

.current-language:hover {
  background: var(--hover-background);
  border-color: var(--hover-border-color);
}

.flag-icon {
  width: 24px;
  height: 18px;
  object-fit: cover;
  border-radius: 2px;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
}

.language-name {
  flex: 1;
  font-size: 14px;
  font-weight: 500;
  color: var(--text-color);
}

.dropdown-icon {
  transition: transform 0.2s ease;
  color: var(--icon-color);
}

.dropdown-icon.open {
  transform: rotate(180deg);
}

.language-dropdown {
  position: absolute;
  top: calc(100% + 4px);
  left: 0;
  right: auto;
  min-width: 100%;
  background: var(--background);
  border: 1px solid var(--border-color);
  border-radius: 6px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  overflow: hidden;
  animation: dropdownSlide 0.2s ease;
  max-height: 300px;
  overflow-y: auto;
}

/* Opens upward when there isn't room below (see direction / dropUp). */
.language-dropdown.drop-up {
  top: auto;
  bottom: calc(100% + 4px);
  animation-name: dropdownSlideUp;
}

/* Anchors to the right edge when a left-anchored menu would overflow (see align / alignRight). */
.language-dropdown.align-right {
  left: auto;
  right: 0;
}

@keyframes dropdownSlide {
  from {
    opacity: 0;
    transform: translateY(-8px);
  }

  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes dropdownSlideUp {
  from {
    opacity: 0;
    transform: translateY(8px);
  }

  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.language-option {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 12px;
  cursor: pointer;
  transition: background 0.15s ease;
}

.language-option:hover {
  background: var(--hover-background);
}

.language-option.selected {
  background: var(--selected-background);
  color: var(--selected-text-color);
}

.language-option .language-name {
  flex: 1;
}

.check-icon {
  color: var(--selected-text-color);
}

/* Scrollbar styling (optional) */
.language-dropdown::-webkit-scrollbar {
  width: 6px;
}

.language-dropdown::-webkit-scrollbar-track {
  background: transparent;
}

.language-dropdown::-webkit-scrollbar-thumb {
  background: var(--scrollbar-color, #cccccc);
  border-radius: 3px;
}

.language-dropdown::-webkit-scrollbar-thumb:hover {
  background: var(--scrollbar-hover-color, #999999);
}`;
}
